controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
hello_route:
    path: /index
    controller: App\Controller\HomeController::index
dashboard:
    path: /admin
    controller: App\Controller\Admin\AdminDashboardController::index
